coverage:
  round: down
  range: '40...100'
  status:
    patch:
      default:
        target: 40%
        informational: true
    project:
      default:
        target: auto
        threshold: 0%
        informational: true