// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package domain

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson57a14e87DecodeGithubComPatradenYaPracticumGoShortlyInternalAppDomain(in *jlexer.Lexer, out *URLMapping) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "short_url":
			out.Slug = Slug(in.String())
		case "original_url":
			out.OriginalURL = OriginalURL(in.String())
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				copy(out.UserID[:], in.Bytes())
			}
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "expires_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ExpiresAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson57a14e87EncodeGithubComPatradenYaPracticumGoShortlyInternalAppDomain(out *jwriter.Writer, in URLMapping) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"short_url\":"
		out.RawString(prefix[1:])
		out.String(string(in.Slug))
	}
	{
		const prefix string = ",\"original_url\":"
		out.RawString(prefix)
		out.String(string(in.OriginalURL))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.Base64Bytes(in.UserID[:])
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"expires_at\":"
		out.RawString(prefix)
		out.Raw((in.ExpiresAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v URLMapping) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson57a14e87EncodeGithubComPatradenYaPracticumGoShortlyInternalAppDomain(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v URLMapping) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson57a14e87EncodeGithubComPatradenYaPracticumGoShortlyInternalAppDomain(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *URLMapping) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson57a14e87DecodeGithubComPatradenYaPracticumGoShortlyInternalAppDomain(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *URLMapping) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson57a14e87DecodeGithubComPatradenYaPracticumGoShortlyInternalAppDomain(l, v)
}
