// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: shortener/v1/shortener.proto

package api

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLRequest) Reset() {
	*x = ShortenURLRequest{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLRequest) ProtoMessage() {}

func (x *ShortenURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLRequest.ProtoReflect.Descriptor instead.
func (*ShortenURLRequest) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ShortenURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLResponse) Reset() {
	*x = ShortenURLResponse{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLResponse) ProtoMessage() {}

func (x *ShortenURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLResponse.ProtoReflect.Descriptor instead.
func (*ShortenURLResponse) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenURLResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type GetOriginalURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalURLRequest) Reset() {
	*x = GetOriginalURLRequest{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalURLRequest) ProtoMessage() {}

func (x *GetOriginalURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalURLRequest.ProtoReflect.Descriptor instead.
func (*GetOriginalURLRequest) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *GetOriginalURLRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type GetOriginalURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalURLResponse) Reset() {
	*x = GetOriginalURLResponse{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalURLResponse) ProtoMessage() {}

func (x *GetOriginalURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalURLResponse.ProtoReflect.Descriptor instead.
func (*GetOriginalURLResponse) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *GetOriginalURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_shortener_v1_shortener_proto protoreflect.FileDescriptor

const file_shortener_v1_shortener_proto_rawDesc = "" +
	"\n" +
	"\x1cshortener/v1/shortener.proto\x12\fshortener.v1\x1a\x1bbuf/validate/validate.proto\"2\n" +
	"\x11ShortenURLRequest\x12\x1d\n" +
	"\x03url\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\x88\x01\x01R\x03url\"(\n" +
	"\x12ShortenURLResponse\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"7\n" +
	"\x15GetOriginalURLRequest\x12\x1e\n" +
	"\x04slug\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x06R\x04slug\"*\n" +
	"\x16GetOriginalURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2\xc3\x01\n" +
	"\x13URLShortenerService\x12O\n" +
	"\n" +
	"ShortenURL\x12\x1f.shortener.v1.ShortenURLRequest\x1a .shortener.v1.ShortenURLResponse\x12[\n" +
	"\x0eGetOriginalURL\x12#.shortener.v1.GetOriginalURLRequest\x1a$.shortener.v1.GetOriginalURLResponseB\xa4\x01\n" +
	"\x10com.shortener.v1B\x0eShortenerProtoP\x01Z/github.com/patraden/ya-practicum-go-shortly/api\xa2\x02\x03SXX\xaa\x02\fShortener.V1\xca\x02\fShortener\\V1\xe2\x02\x18Shortener\\V1\\GPBMetadata\xea\x02\rShortener::V1b\x06proto3"

var (
	file_shortener_v1_shortener_proto_rawDescOnce sync.Once
	file_shortener_v1_shortener_proto_rawDescData []byte
)

func file_shortener_v1_shortener_proto_rawDescGZIP() []byte {
	file_shortener_v1_shortener_proto_rawDescOnce.Do(func() {
		file_shortener_v1_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shortener_v1_shortener_proto_rawDesc), len(file_shortener_v1_shortener_proto_rawDesc)))
	})
	return file_shortener_v1_shortener_proto_rawDescData
}

var file_shortener_v1_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shortener_v1_shortener_proto_goTypes = []any{
	(*ShortenURLRequest)(nil),      // 0: shortener.v1.ShortenURLRequest
	(*ShortenURLResponse)(nil),     // 1: shortener.v1.ShortenURLResponse
	(*GetOriginalURLRequest)(nil),  // 2: shortener.v1.GetOriginalURLRequest
	(*GetOriginalURLResponse)(nil), // 3: shortener.v1.GetOriginalURLResponse
}
var file_shortener_v1_shortener_proto_depIdxs = []int32{
	0, // 0: shortener.v1.URLShortenerService.ShortenURL:input_type -> shortener.v1.ShortenURLRequest
	2, // 1: shortener.v1.URLShortenerService.GetOriginalURL:input_type -> shortener.v1.GetOriginalURLRequest
	1, // 2: shortener.v1.URLShortenerService.ShortenURL:output_type -> shortener.v1.ShortenURLResponse
	3, // 3: shortener.v1.URLShortenerService.GetOriginalURL:output_type -> shortener.v1.GetOriginalURLResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shortener_v1_shortener_proto_init() }
func file_shortener_v1_shortener_proto_init() {
	if File_shortener_v1_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shortener_v1_shortener_proto_rawDesc), len(file_shortener_v1_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shortener_v1_shortener_proto_goTypes,
		DependencyIndexes: file_shortener_v1_shortener_proto_depIdxs,
		MessageInfos:      file_shortener_v1_shortener_proto_msgTypes,
	}.Build()
	File_shortener_v1_shortener_proto = out.File
	file_shortener_v1_shortener_proto_goTypes = nil
	file_shortener_v1_shortener_proto_depIdxs = nil
}
